### ISSUE TITLE
Block `messenger.com` domains.

### ISSUE THREAD

**Issue by mdrakea** [Repsi0/HostsGenerator#1]

**Comment by ghost** [comment]
imagine blocking domains, the scanner found no subdomains

**Comment by mdrakea** [comment]
ah, fair enough

also why not just use uBlock Origin or another blocker

**Comment by Zephia-Sero** [comment]
cause having a hosts file at OS level is much cooler

**Comment by mdrakea** [comment]
good point
~~still just gonna use ublock~~

**Comment by Zephia-Sero** [comment]
done lol
